---

# Configuration tasks for haproxy

- name : Create directory to store splitted configuration
  become : True
  file :
    path  : "{{ haproxy_path_prefix_etc }}/conf.d"
    state : directory


- name : Empty the folder if not already empty
  become : True
  changed_when : False
  command : >
    find {{ haproxy_path_prefix_etc }}/conf.d -name *.cfg -exec rm -f {} \;


- name: Generate the global configuration
  become : True
  changed_when : False
  template :
    src  : "{{ role_path }}/templates/{{ haproxy_version_number }}/global.conf.j2"
    dest : "{{ haproxy_path_prefix_etc }}/conf.d/01-global.cfg"


- name: Generate the default configuration
  become : True
  changed_when : False
  template :
    src  : "{{ role_path }}/templates/{{ haproxy_version_number }}/defaults.conf.j2"
    dest : "{{ haproxy_path_prefix_etc }}/conf.d/02-default.cfg"
  when : haproxy_defaults


- name : Generate the frontends configuration
  become : True
  changed_when : False
  template :
    src  : "{{ role_path }}/templates/{{ haproxy_version_number }}/frontends.conf.j2"
    dest : "{{ haproxy_path_prefix_etc }}/conf.d/03-frontends.cfg"
  when : haproxy_frontends


- name : Generate the backends configuration
  become : True
  changed_when : False
  template :
    src  : "{{ role_path }}/templates/{{ haproxy_version_number }}/backends.conf.j2"
    dest : "{{ haproxy_path_prefix_etc }}/conf.d/04-backends.cfg"
  when : haproxy_backends


- name : Generate the listens configuration
  become : True
  changed_when : False
  template :
    src  : "{{ role_path }}/templates/{{ haproxy_version_number }}/listens.conf.j2"
    dest : "{{ haproxy_path_prefix_etc }}/conf.d/05-listens.cfg"
  when : haproxy_listens


- name : Generate the userlists configuration
  become : True
  changed_when : False
  template :
    src  : "{{ role_path }}/templates/{{ haproxy_version_number }}/userlists.conf.j2"
    dest : "{{ haproxy_path_prefix_etc }}/conf.d/06-userlists.cfg"
  when : haproxy_userlists


- name : Assemble the final configuration file
  become : True
  assemble :
    src    : "{{ haproxy_path_prefix_etc }}/conf.d"
    dest   : "{{ haproxy_config_location }}"
    backup : True
  register : debug_haproxy_assemble
  notify : restart haproxy

